//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FERHRI.DB.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://10.11.203.28/data/NOAA/NCEP/FTPPRD/pub/data/nccf/com/gfs/prod")]
        public string GFSFTPPath05full {
            get {
                return ((string)(this["GFSFTPPath05full"]));
            }
            set {
                this["GFSFTPPath05full"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" ftp://10.11.203.28/data/NOAA/NCEP/FTPPRD/pub/data/nccf/com/gfs/prod0p25")]
        public string GFSFTPPath025 {
            get {
                return ((string)(this["GFSFTPPath025"]));
            }
            set {
                this["GFSFTPPath025"] = value;
            }
        }
    }
}
