//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _TestWCFServiceField.ServiceFieldReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoRectangle", Namespace="http://schemas.datacontract.org/2004/07/FERHRI.Geo")]
    [System.SerializableAttribute()]
    public partial class GeoRectangle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _TestWCFServiceField.ServiceFieldReference.GeoPoint NorthWestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _TestWCFServiceField.ServiceFieldReference.GeoPoint SouthEastField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _TestWCFServiceField.ServiceFieldReference.GeoPoint NorthWest {
            get {
                return this.NorthWestField;
            }
            set {
                if ((object.ReferenceEquals(this.NorthWestField, value) != true)) {
                    this.NorthWestField = value;
                    this.RaisePropertyChanged("NorthWest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _TestWCFServiceField.ServiceFieldReference.GeoPoint SouthEast {
            get {
                return this.SouthEastField;
            }
            set {
                if ((object.ReferenceEquals(this.SouthEastField, value) != true)) {
                    this.SouthEastField = value;
                    this.RaisePropertyChanged("SouthEast");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoPoint", Namespace="http://schemas.datacontract.org/2004/07/FERHRI.Geo")]
    [System.SerializableAttribute()]
    public partial class GeoPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatGrdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonGrdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatGrd {
            get {
                return this.LatGrdField;
            }
            set {
                if ((this.LatGrdField.Equals(value) != true)) {
                    this.LatGrdField = value;
                    this.RaisePropertyChanged("LatGrd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LonGrd {
            get {
                return this.LonGrdField;
            }
            set {
                if ((this.LonGrdField.Equals(value) != true)) {
                    this.LonGrdField = value;
                    this.RaisePropertyChanged("LonGrd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Field", Namespace="http://schemas.datacontract.org/2004/07/FERHRI")]
    [System.SerializableAttribute()]
    public partial class Field : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _TestWCFServiceField.ServiceFieldReference.EnumFieldFormat FieldFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _TestWCFServiceField.ServiceFieldReference.Grid GridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PredictTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _TestWCFServiceField.ServiceFieldReference.EnumFieldFormat FieldFormat {
            get {
                return this.FieldFormatField;
            }
            set {
                if ((this.FieldFormatField.Equals(value) != true)) {
                    this.FieldFormatField = value;
                    this.RaisePropertyChanged("FieldFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _TestWCFServiceField.ServiceFieldReference.Grid Grid {
            get {
                return this.GridField;
            }
            set {
                if ((object.ReferenceEquals(this.GridField, value) != true)) {
                    this.GridField = value;
                    this.RaisePropertyChanged("Grid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PredictTime {
            get {
                return this.PredictTimeField;
            }
            set {
                if ((this.PredictTimeField.Equals(value) != true)) {
                    this.PredictTimeField = value;
                    this.RaisePropertyChanged("PredictTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grid", Namespace="http://schemas.datacontract.org/2004/07/FERHRI.Geo")]
    [System.SerializableAttribute()]
    public partial class Grid : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatStartMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatStepMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] LatsMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonStartMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LonStepMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] LonsMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatStartMin {
            get {
                return this.LatStartMinField;
            }
            set {
                if ((this.LatStartMinField.Equals(value) != true)) {
                    this.LatStartMinField = value;
                    this.RaisePropertyChanged("LatStartMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LatStepMin {
            get {
                return this.LatStepMinField;
            }
            set {
                if ((this.LatStepMinField.Equals(value) != true)) {
                    this.LatStepMinField = value;
                    this.RaisePropertyChanged("LatStepMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] LatsMin {
            get {
                return this.LatsMinField;
            }
            set {
                if ((object.ReferenceEquals(this.LatsMinField, value) != true)) {
                    this.LatsMinField = value;
                    this.RaisePropertyChanged("LatsMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LonStartMin {
            get {
                return this.LonStartMinField;
            }
            set {
                if ((this.LonStartMinField.Equals(value) != true)) {
                    this.LonStartMinField = value;
                    this.RaisePropertyChanged("LonStartMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LonStepMin {
            get {
                return this.LonStepMinField;
            }
            set {
                if ((this.LonStepMinField.Equals(value) != true)) {
                    this.LonStepMinField = value;
                    this.RaisePropertyChanged("LonStepMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] LonsMin {
            get {
                return this.LonsMinField;
            }
            set {
                if ((object.ReferenceEquals(this.LonsMinField, value) != true)) {
                    this.LonsMinField = value;
                    this.RaisePropertyChanged("LonsMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumFieldFormat", Namespace="http://schemas.datacontract.org/2004/07/FERHRI")]
    public enum EnumFieldFormat : long {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GRID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XYZ = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Method", Namespace="http://schemas.datacontract.org/2004/07/FERHRI.Amur.Meta")]
    [System.SerializableAttribute()]
    public partial class Method : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _TestWCFServiceField.ServiceFieldReference.MethodForecast MethodForecastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> MethodOutputStoreParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _TestWCFServiceField.ServiceFieldReference.MethodForecast MethodForecast {
            get {
                return this.MethodForecastField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodForecastField, value) != true)) {
                    this.MethodForecastField = value;
                    this.RaisePropertyChanged("MethodForecast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> MethodOutputStoreParameters {
            get {
                return this.MethodOutputStoreParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodOutputStoreParametersField, value) != true)) {
                    this.MethodOutputStoreParametersField = value;
                    this.RaisePropertyChanged("MethodOutputStoreParameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodForecast", Namespace="http://schemas.datacontract.org/2004/07/FERHRI.Amur.Meta")]
    [System.SerializableAttribute()]
    public partial class MethodForecast : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] DateIniHoursUTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] LeadTimesHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _TestWCFServiceField.ServiceFieldReference.Method MethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] DateIniHoursUTC {
            get {
                return this.DateIniHoursUTCField;
            }
            set {
                if ((object.ReferenceEquals(this.DateIniHoursUTCField, value) != true)) {
                    this.DateIniHoursUTCField = value;
                    this.RaisePropertyChanged("DateIniHoursUTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] LeadTimesHours {
            get {
                return this.LeadTimesHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadTimesHoursField, value) != true)) {
                    this.LeadTimesHoursField = value;
                    this.RaisePropertyChanged("LeadTimesHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _TestWCFServiceField.ServiceFieldReference.Method Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFieldReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Open", ReplyAction="http://tempuri.org/IService/OpenResponse")]
        long Open(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Open", ReplyAction="http://tempuri.org/IService/OpenResponse")]
        System.Threading.Tasks.Task<long> OpenAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Close", ReplyAction="http://tempuri.org/IService/CloseResponse")]
        void Close(long hSvc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Close", ReplyAction="http://tempuri.org/IService/CloseResponse")]
        System.Threading.Tasks.Task CloseAsync(long hSvc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CloseByUserName", ReplyAction="http://tempuri.org/IService/CloseByUserNameResponse")]
        void CloseByUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CloseByUserName", ReplyAction="http://tempuri.org/IService/CloseByUserNameResponse")]
        System.Threading.Tasks.Task CloseByUserNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataByCatalogs", ReplyAction="http://tempuri.org/IService/GetDataByCatalogsResponse")]
        _TestWCFServiceField.ServiceFieldReference.Field[][][] GetDataByCatalogs(long hSvc, System.DateTime dateIni, int[] catalogIds, _TestWCFServiceField.ServiceFieldReference.GeoRectangle[] grs, double[] leadTimes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataByCatalogs", ReplyAction="http://tempuri.org/IService/GetDataByCatalogsResponse")]
        System.Threading.Tasks.Task<_TestWCFServiceField.ServiceFieldReference.Field[][][]> GetDataByCatalogsAsync(long hSvc, System.DateTime dateIni, int[] catalogIds, _TestWCFServiceField.ServiceFieldReference.GeoRectangle[] grs, double[] leadTimes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMethods", ReplyAction="http://tempuri.org/IService/GetMethodsResponse")]
        _TestWCFServiceField.ServiceFieldReference.Method[] GetMethods(long hSvc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMethods", ReplyAction="http://tempuri.org/IService/GetMethodsResponse")]
        System.Threading.Tasks.Task<_TestWCFServiceField.ServiceFieldReference.Method[]> GetMethodsAsync(long hSvc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : _TestWCFServiceField.ServiceFieldReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<_TestWCFServiceField.ServiceFieldReference.IService>, _TestWCFServiceField.ServiceFieldReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long Open(string userName, string password) {
            return base.Channel.Open(userName, password);
        }
        
        public System.Threading.Tasks.Task<long> OpenAsync(string userName, string password) {
            return base.Channel.OpenAsync(userName, password);
        }
        
        public void Close(long hSvc) {
            base.Channel.Close(hSvc);
        }
        
        public System.Threading.Tasks.Task CloseAsync(long hSvc) {
            return base.Channel.CloseAsync(hSvc);
        }
        
        public void CloseByUserName(string userName) {
            base.Channel.CloseByUserName(userName);
        }
        
        public System.Threading.Tasks.Task CloseByUserNameAsync(string userName) {
            return base.Channel.CloseByUserNameAsync(userName);
        }
        
        public _TestWCFServiceField.ServiceFieldReference.Field[][][] GetDataByCatalogs(long hSvc, System.DateTime dateIni, int[] catalogIds, _TestWCFServiceField.ServiceFieldReference.GeoRectangle[] grs, double[] leadTimes) {
            return base.Channel.GetDataByCatalogs(hSvc, dateIni, catalogIds, grs, leadTimes);
        }
        
        public System.Threading.Tasks.Task<_TestWCFServiceField.ServiceFieldReference.Field[][][]> GetDataByCatalogsAsync(long hSvc, System.DateTime dateIni, int[] catalogIds, _TestWCFServiceField.ServiceFieldReference.GeoRectangle[] grs, double[] leadTimes) {
            return base.Channel.GetDataByCatalogsAsync(hSvc, dateIni, catalogIds, grs, leadTimes);
        }
        
        public _TestWCFServiceField.ServiceFieldReference.Method[] GetMethods(long hSvc) {
            return base.Channel.GetMethods(hSvc);
        }
        
        public System.Threading.Tasks.Task<_TestWCFServiceField.ServiceFieldReference.Method[]> GetMethodsAsync(long hSvc) {
            return base.Channel.GetMethodsAsync(hSvc);
        }
    }
}
